# Generated by Django 2.2.7 on 2020-01-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='spayed',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('k', 'Not known')], max_length=1, null=True),
        ),
    ]
